import { expect, test } from '@playwright/test'

test('Learn opens directly to a study card and remains usable offline on mobile', async ({ page, context }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto('/learn-japanese-app/')
  if (await page.getByRole('heading', { name: 'Choose a profile' }).count()) await page.getByRole('button', { name: /Kevin/ }).click()
  await expect(page.getByRole('heading', { name: 'Learn Japanese' })).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Main navigation' })).toBeVisible()
  for (const name of ['Learn', 'Practice', 'Progress', 'More']) await expect(page.getByRole('button', { name })).toBeVisible()
  const manifest = await page.locator('link[rel="manifest"]').getAttribute('href')
  expect(manifest).toContain('manifest.webmanifest')
  const appManifest = await page.evaluate(async (href) => fetch(href!).then((response) => response.json()), manifest)
  expect(appManifest).toMatchObject({ name: 'Learn Japanese', short_name: 'Japanese', display: 'standalone' })
  const card = page.getByRole('region', { name: 'Daily study card' })
  await expect(card).toBeVisible()
  await expect(card.getByRole('heading')).toBeVisible()
  await expect(card.getByRole('textbox')).toHaveCount(0)
  await expect(card).not.toContainText(/type the japanese|write .* japanese|meaning .* japanese/i)
  await expect(page.getByRole('button', { name: 'Continue', exact: true })).toHaveCount(0)
  await expect(page.getByText('YOUR FIRST COURSE')).toHaveCount(0)
  await expect(card.getByRole('group', { name: 'Review rating' })).toHaveCount(0)
  await card.getByRole('button', { name: 'Show answer' }).click()
  for (const rating of ['Again', 'Hard', 'Good', 'Easy']) await expect(card.getByRole('button', { name: rating, exact: true })).toBeVisible()
  await card.getByRole('button', { name: 'Hard', exact: true }).click()
  await page.reload()
  await expect(page.locator('.kana-review')).toBeVisible()
  await expect.poll(() => page.evaluate(() => Boolean(navigator.serviceWorker.controller))).toBe(true)
  const nav = page.getByRole('navigation', { name: 'Main navigation' })
  const bounds = await nav.boundingBox()
  expect(bounds).not.toBeNull()
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(page.viewportSize()!.height)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await context.setOffline(true)
  await page.reload()
  await expect(page.locator('.kana-review')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Show answer' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('navigation fits a wider responsive viewport', async ({ page }) => {
  await page.setViewportSize({ width: 1024, height: 768 })
  await page.goto('/learn-japanese-app/')
  if (await page.getByRole('heading', { name: 'Choose a profile' }).count()) await page.getByRole('button', { name: /Kevin/ }).click()
  const nav = page.getByRole('navigation', { name: 'Main navigation' })
  await expect(nav).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
