import type { ContentId, VocabularyConcept } from "../lib/content/types.ts";

const id = (value: string) => value as ContentId;

/** Small canonical seed set; kanji entries always include a learner-visible kana reading. */
export const vocabularyFixtures: readonly VocabularyConcept[] = [
  {
    id: id("vocab-neko"), written: "猫", reading: "ねこ", meanings: ["cat"], partOfSpeech: "noun", tags: ["animals", "beginner"],
    examples: [{ written: "猫がいます。", reading: "ねこがいます。", meaning: "There is a cat." }],
  },
  {
    id: id("vocab-mizu"), written: "水", reading: "みず", meanings: ["water"], partOfSpeech: "noun", tags: ["food", "beginner"],
  },
  {
    id: id("vocab-watashi"), written: "わたし", reading: "わたし", meanings: ["I", "me"], partOfSpeech: "pronoun", tags: ["identity", "beginner"],
    examples: [{ written: "わたしは学生です。", reading: "わたしはがくせいです。", meaning: "I am a student." }],
  },
  {
    id: id("vocab-gakusei"), written: "学生", reading: "がくせい", meanings: ["student"], partOfSpeech: "noun", tags: ["identity", "beginner"],
    examples: [{ written: "わたしは学生です。", reading: "わたしはがくせいです。", meaning: "I am a student." }],
  },
  {
    id: id("vocab-sensei"), written: "先生", reading: "せんせい", meanings: ["teacher"], partOfSpeech: "noun", tags: ["identity", "beginner"],
  },
  {
    id: id("vocab-kevin"), written: "ケビン", reading: "ケビン", meanings: ["Kevin"], partOfSpeech: "proper noun", tags: ["identity", "name"],
    examples: [{ written: "わたしはケビンです。", reading: "わたしはケビンです。", meaning: "I am Kevin." }],
  },
  { id: id("vocab-hito"), written: "人", reading: "ひと", meanings: ["person", "people"], partOfSpeech: "noun", tags: ["people", "beginner"] },
  { id: id("vocab-kazoku"), written: "家族", reading: "かぞく", meanings: ["family"], partOfSpeech: "noun", tags: ["family", "beginner"] },
  { id: id("vocab-haha"), written: "母", reading: "はは", meanings: ["my mother"], partOfSpeech: "noun", tags: ["family", "beginner"], examples: [{ written: "母は先生です。", reading: "はははせんせいです。", meaning: "My mother is a teacher." }] },
  { id: id("vocab-chichi"), written: "父", reading: "ちち", meanings: ["my father"], partOfSpeech: "noun", tags: ["family", "beginner"] },
  { id: id("vocab-ani"), written: "兄", reading: "あに", meanings: ["my older brother"], partOfSpeech: "noun", tags: ["family", "beginner"] },
  { id: id("vocab-ane"), written: "姉", reading: "あね", meanings: ["my older sister"], partOfSpeech: "noun", tags: ["family", "beginner"] },
  { id: id("vocab-okaasan"), written: "お母さん", reading: "おかあさん", meanings: ["mother"], partOfSpeech: "noun", tags: ["family", "politeness"] },
  { id: id("vocab-otousan"), written: "お父さん", reading: "おとうさん", meanings: ["father"], partOfSpeech: "noun", tags: ["family", "politeness"] },
  { id: id("vocab-zero"), written: "零", reading: "れい", meanings: ["zero"], partOfSpeech: "number", tags: ["numbers", "beginner"] },
  { id: id("vocab-ichi"), written: "一", reading: "いち", meanings: ["one"], partOfSpeech: "number", tags: ["numbers", "beginner"] },
  { id: id("vocab-ni"), written: "二", reading: "に", meanings: ["two"], partOfSpeech: "number", tags: ["numbers", "beginner"] },
  { id: id("vocab-san"), written: "三", reading: "さん", meanings: ["three"], partOfSpeech: "number", tags: ["numbers", "beginner"] },
  { id: id("vocab-yon"), written: "四", reading: "よん", meanings: ["four"], partOfSpeech: "number", tags: ["numbers", "beginner"] },
  { id: id("vocab-go"), written: "五", reading: "ご", meanings: ["five"], partOfSpeech: "number", tags: ["numbers", "beginner"] },
  { id: id("vocab-roku"), written: "六", reading: "ろく", meanings: ["six"], partOfSpeech: "number", tags: ["numbers", "beginner"] },
  { id: id("vocab-nana"), written: "七", reading: "なな", meanings: ["seven"], partOfSpeech: "number", tags: ["numbers", "beginner"] },
  { id: id("vocab-hachi"), written: "八", reading: "はち", meanings: ["eight"], partOfSpeech: "number", tags: ["numbers", "beginner"] },
  { id: id("vocab-kyuu"), written: "九", reading: "きゅう", meanings: ["nine"], partOfSpeech: "number", tags: ["numbers", "beginner"] },
  { id: id("vocab-juu"), written: "十", reading: "じゅう", meanings: ["ten"], partOfSpeech: "number", tags: ["numbers", "beginner"] },
  { id: id("vocab-nanji"), written: "何時", reading: "なんじ", meanings: ["what time"], partOfSpeech: "question word", tags: ["time", "beginner"] },
  { id: id("vocab-fun"), written: "分", reading: "ふん", meanings: ["minute"], partOfSpeech: "counter", tags: ["time", "beginner"] },
  { id: id("vocab-han"), written: "半", reading: "はん", meanings: ["half", "half past"], partOfSpeech: "time expression", tags: ["time", "beginner"] },
  { id: id("vocab-hitori"), written: "一人", reading: "ひとり", meanings: ["one person"], partOfSpeech: "counter phrase", tags: ["counters", "people", "beginner"] },
  { id: id("vocab-futari"), written: "二人", reading: "ふたり", meanings: ["two people"], partOfSpeech: "counter phrase", tags: ["counters", "people", "beginner"] },
  { id: id("vocab-gohan"), written: "ご飯", reading: "ごはん", meanings: ["rice", "meal"], partOfSpeech: "noun", tags: ["food", "beginner"] },
  { id: id("vocab-pan"), written: "パン", reading: "パン", meanings: ["bread"], partOfSpeech: "noun", tags: ["food", "beginner"] },
  { id: id("vocab-sushi"), written: "寿司", reading: "すし", meanings: ["sushi"], partOfSpeech: "noun", tags: ["food", "beginner"] },
  { id: id("vocab-ramen"), written: "ラーメン", reading: "ラーメン", meanings: ["ramen"], partOfSpeech: "noun", tags: ["food", "beginner"] },
  { id: id("vocab-ocha"), written: "お茶", reading: "おちゃ", meanings: ["tea"], partOfSpeech: "noun", tags: ["drink", "beginner"] },
  { id: id("vocab-coffee"), written: "コーヒー", reading: "コーヒー", meanings: ["coffee"], partOfSpeech: "noun", tags: ["drink", "beginner"] },
  { id: id("vocab-uchi"), written: "うち", reading: "うち", meanings: ["home"], partOfSpeech: "noun", tags: ["places", "beginner"] },
  { id: id("vocab-gakkou"), written: "学校", reading: "がっこう", meanings: ["school"], partOfSpeech: "noun", tags: ["places", "beginner"] },
  { id: id("vocab-eki"), written: "駅", reading: "えき", meanings: ["station"], partOfSpeech: "noun", tags: ["places", "beginner"] },
  { id: id("vocab-mise"), written: "店", reading: "みせ", meanings: ["shop", "store"], partOfSpeech: "noun", tags: ["places", "beginner"] },
  { id: id("vocab-kore"), written: "これ", reading: "これ", meanings: ["this thing"], partOfSpeech: "demonstrative", tags: ["demonstratives", "beginner"] },
  { id: id("vocab-sore"), written: "それ", reading: "それ", meanings: ["that thing near the listener"], partOfSpeech: "demonstrative", tags: ["demonstratives", "beginner"] },
  { id: id("vocab-are"), written: "あれ", reading: "あれ", meanings: ["that thing over there"], partOfSpeech: "demonstrative", tags: ["demonstratives", "beginner"] },
  { id: id("vocab-dore"), written: "どれ", reading: "どれ", meanings: ["which thing"], partOfSpeech: "question word", tags: ["demonstratives", "beginner"] },
  { id: id("vocab-koko"), written: "ここ", reading: "ここ", meanings: ["here; this place"], partOfSpeech: "place word", tags: ["places", "demonstratives", "beginner"] },
  { id: id("vocab-soko"), written: "そこ", reading: "そこ", meanings: ["there; that place near the listener"], partOfSpeech: "place word", tags: ["places", "demonstratives", "beginner"] },
  { id: id("vocab-asoko"), written: "あそこ", reading: "あそこ", meanings: ["over there"], partOfSpeech: "place word", tags: ["places", "demonstratives", "beginner"] },
  { id: id("vocab-doko"), written: "どこ", reading: "どこ", meanings: ["where"], partOfSpeech: "question word", tags: ["places", "demonstratives", "beginner"] },
  { id: id("vocab-iku"), written: "行く", reading: "いく", meanings: ["go"], partOfSpeech: "verb", tags: ["routines", "beginner"], examples: [{ written: "学校へ行きます。", reading: "がっこうへいきます。", meaning: "I go to school." }] },
  { id: id("vocab-taberu"), written: "食べる", reading: "たべる", meanings: ["eat"], partOfSpeech: "verb", tags: ["routines", "beginner"], examples: [{ written: "ごはんを食べます。", reading: "ごはんをたべます。", meaning: "I eat a meal." }] },
  { id: id("vocab-nomu"), written: "飲む", reading: "のむ", meanings: ["drink"], partOfSpeech: "verb", tags: ["routines", "beginner"], examples: [{ written: "水を飲みます。", reading: "みずをのみます。", meaning: "I drink water." }] },
  { id: id("vocab-benkyou-suru"), written: "勉強する", reading: "べんきょうする", meanings: ["study"], partOfSpeech: "verb", tags: ["routines", "beginner"], examples: [{ written: "うちで勉強します。", reading: "うちでべんきょうします。", meaning: "I study at home." }] },
  { id: id("vocab-oishii"), written: "おいしい", reading: "おいしい", meanings: ["tasty", "delicious"], partOfSpeech: "i-adjective", tags: ["descriptions", "beginner"] },
  { id: id("vocab-isogashii"), written: "忙しい", reading: "いそがしい", meanings: ["busy"], partOfSpeech: "i-adjective", tags: ["descriptions", "beginner"] },
  { id: id("vocab-tanoshii"), written: "楽しい", reading: "たのしい", meanings: ["fun", "enjoyable"], partOfSpeech: "i-adjective", tags: ["descriptions", "beginner"] },
  { id: id("vocab-asagohan"), written: "朝ごはん", reading: "あさごはん", meanings: ["breakfast"], partOfSpeech: "noun", tags: ["food", "routines", "beginner"] },
];
